// Code generated by cmd/reset; DO NOT EDIT.

package models

func (m *Metrics) Reset() {
	if m == nil {
		return
	}
	m.ID = ""
	m.MType = *new(MetricType)
	if m.Delta != nil {
		*m.Delta = 0
	}
	if m.Value != nil {
		*m.Value = 0
	}
}
