// Command reset генерирует методы Reset() для структур с комментарием // generate:reset.
//
// Запуск из корня модуля (или любой поддиректории):
//
//	go run ./cmd/reset
//
// Для каждого пакета со структурами-кандидатами создаётся файл reset.gen.go.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

const (
	markerComment = "generate:reset"
	outFileName   = "reset.gen.go"
)

func main() {
	root, err := findModuleRoot()
	if err != nil {
		panic(err)
	}
	if err := generateAll(root); err != nil {
		panic(err)
	}
}

func findModuleRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return wd, nil
		}
		dir = parent
	}
}

func generateAll(root string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		base := d.Name()
		if shouldSkipDir(base) && path != root {
			return filepath.SkipDir
		}
		return generatePackage(path)
	})
}

func shouldSkipDir(name string) bool {
	switch name {
	case "vendor", "testdata", "node_modules", ".git", ".idea", ".vscode":
		return true
	}
	return strings.HasPrefix(name, ".")
}

type pkgInfo struct {
	name       string
	dir        string
	structDefs map[string]*ast.StructType // локальные структуры пакета
	hasReset   map[string]bool            // типы с Reset (уже есть или будут сгенерированы)
	targets    []targetStruct             // кандидаты на генерацию
}

type targetStruct struct {
	name   string
	fields []*ast.Field
}

func generatePackage(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	fset := token.NewFileSet()
	filesByPkg := make(map[string][]*ast.File)

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == outFileName {
			continue
		}
		path := filepath.Join(dir, name)
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		pkgName := f.Name.Name
		if strings.HasSuffix(pkgName, "_test") {
			continue
		}
		filesByPkg[pkgName] = append(filesByPkg[pkgName], f)
	}

	for pkgName, files := range filesByPkg {
		info := &pkgInfo{
			name:       pkgName,
			dir:        dir,
			structDefs: make(map[string]*ast.StructType),
			hasReset:   make(map[string]bool),
		}
		collectPackage(info, files)
		if len(info.targets) == 0 {
			_ = os.Remove(filepath.Join(dir, outFileName))
			continue
		}
		if err := writeResetFile(info); err != nil {
			return err
		}
	}
	return nil
}

func collectPackage(info *pkgInfo, files []*ast.File) {
	for _, file := range files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				if d.Tok != token.TYPE {
					continue
				}
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					info.structDefs[ts.Name.Name] = st
					if hasGenerateReset(d.Doc, ts.Doc) {
						info.hasReset[ts.Name.Name] = true
						info.targets = append(info.targets, targetStruct{
							name:   ts.Name.Name,
							fields: st.Fields.List,
						})
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil || d.Name.Name != "Reset" || d.Recv.NumFields() != 1 {
					continue
				}
				recvType := d.Recv.List[0].Type
				if star, ok := recvType.(*ast.StarExpr); ok {
					recvType = star.X
				}
				if id, ok := recvType.(*ast.Ident); ok {
					info.hasReset[id.Name] = true
				}
			}
		}
	}
}

func hasGenerateReset(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc == nil {
			continue
		}
		for _, c := range doc.List {
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			text = strings.TrimSpace(strings.TrimPrefix(text, "/*"))
			text = strings.TrimSpace(strings.TrimSuffix(text, "*/"))
			if strings.Contains(text, markerComment) {
				return true
			}
		}
	}
	return false
}

func writeResetFile(info *pkgInfo) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	buf.WriteString("package ")
	buf.WriteString(info.name)
	buf.WriteString("\n\n")

	for _, t := range info.targets {
		recv := receiverName(t.name)
		fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", recv, t.name)
		fmt.Fprintf(&buf, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)
		for _, field := range t.fields {
			writeFieldResets(&buf, info, recv, field)
		}
		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("%s/%s: format: %w\n---\n%s", info.dir, outFileName, err, buf.String())
	}
	outPath := filepath.Join(info.dir, outFileName)
	return os.WriteFile(outPath, formatted, 0o644)
}

func receiverName(typeName string) string {
	r, size := utf8.DecodeRuneInString(typeName)
	if r == utf8.RuneError && size == 0 {
		return "v"
	}
	return string(unicode.ToLower(r))
}

func writeFieldResets(buf *bytes.Buffer, info *pkgInfo, recv string, field *ast.Field) {
	names := fieldNames(field)
	for _, name := range names {
		sel := recv + "." + name
		writeExprReset(buf, info, sel, field.Type)
	}
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, n := range field.Names {
			if n.Name == "_" {
				continue
			}
			names = append(names, n.Name)
		}
		return names
	}
	// Встроенное поле: имя — идентификатор типа.
	switch t := field.Type.(type) {
	case *ast.Ident:
		return []string{t.Name}
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return []string{id.Name}
		}
	case *ast.SelectorExpr:
		return []string{t.Sel.Name}
	}
	return nil
}

// writeExprReset пишет операторы сброса для выражения типа typ.
func writeExprReset(buf *bytes.Buffer, info *pkgInfo, sel string, typ ast.Expr) {
	switch t := typ.(type) {
	case *ast.Ident:
		writeIdentReset(buf, info, sel, t.Name)
	case *ast.StarExpr:
		fmt.Fprintf(buf, "\tif %s != nil {\n", sel)
		writePointerElemReset(buf, info, sel, t.X)
		buf.WriteString("\t}\n")
	case *ast.ArrayType:
		if t.Len == nil {
			// Слайс: обрезаем длину, capacity сохраняем.
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", sel, sel)
			return
		}
		// Массив — нулевое значение целиком.
		fmt.Fprintf(buf, "\t%s = %s\n", sel, zeroValue(typeString(typ)))
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s)\n", sel)
	case *ast.StructType:
		// Анонимная структура без Reset — присваиваем нулевое значение.
		fmt.Fprintf(buf, "\t%s = %s\n", sel, zeroValue(typeString(typ)))
	case *ast.SelectorExpr:
		// Тип из другого пакета: универсальный сброс через *new(T).
		fmt.Fprintf(buf, "\t%s = %s\n", sel, zeroValue(typeString(typ)))
	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		fmt.Fprintf(buf, "\t%s = nil\n", sel)
	default:
		fmt.Fprintf(buf, "\t%s = %s\n", sel, zeroValue(typeString(typ)))
	}
}

func writeIdentReset(buf *bytes.Buffer, info *pkgInfo, sel, typeName string) {
	if isBuiltinNumeric(typeName) || typeName == "byte" || typeName == "rune" {
		fmt.Fprintf(buf, "\t%s = 0\n", sel)
		return
	}
	switch typeName {
	case "bool":
		fmt.Fprintf(buf, "\t%s = false\n", sel)
		return
	case "string":
		fmt.Fprintf(buf, "\t%s = \"\"\n", sel)
		return
	case "any", "error":
		fmt.Fprintf(buf, "\t%s = nil\n", sel)
		return
	}

	if info.hasReset[typeName] {
		fmt.Fprintf(buf, "\t%s.Reset()\n", sel)
		return
	}
	if _, isStruct := info.structDefs[typeName]; isStruct {
		fmt.Fprintf(buf, "\t%s = %s{}\n", sel, typeName)
		return
	}
	// Именованный тип (например, type MetricType string).
	fmt.Fprintf(buf, "\t%s = %s\n", sel, zeroValue(typeName))
}

func writePointerElemReset(buf *bytes.Buffer, info *pkgInfo, ptrSel string, elem ast.Expr) {
	switch t := elem.(type) {
	case *ast.Ident:
		if info.hasReset[t.Name] {
			// Метод Reset у указателя на структуру сам проверяет nil-получатель,
			// но мы уже внутри if ptr != nil.
			fmt.Fprintf(buf, "\t\t%s.Reset()\n", ptrSel)
			return
		}
		if isBuiltinNumeric(t.Name) || t.Name == "byte" || t.Name == "rune" {
			fmt.Fprintf(buf, "\t\t*%s = 0\n", ptrSel)
			return
		}
		switch t.Name {
		case "bool":
			fmt.Fprintf(buf, "\t\t*%s = false\n", ptrSel)
		case "string":
			fmt.Fprintf(buf, "\t\t*%s = \"\"\n", ptrSel)
		default:
			if _, isStruct := info.structDefs[t.Name]; isStruct {
				fmt.Fprintf(buf, "\t\t*%s = %s{}\n", ptrSel, t.Name)
			} else {
				fmt.Fprintf(buf, "\t\t*%s = %s\n", ptrSel, zeroValue(t.Name))
			}
		}
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(buf, "\t\t*%s = (*%s)[:0]\n", ptrSel, ptrSel)
			return
		}
		fmt.Fprintf(buf, "\t\t*%s = %s\n", ptrSel, zeroValue(typeString(elem)))
	case *ast.MapType:
		fmt.Fprintf(buf, "\t\tclear(*%s)\n", ptrSel)
	case *ast.StarExpr:
		// Указатель на указатель: сбрасываем «внутреннее» значение.
		fmt.Fprintf(buf, "\t\tif *%s != nil {\n", ptrSel)
		inner := "(*" + ptrSel + ")"
		writePointerElemReset(buf, info, inner, t.X)
		buf.WriteString("\t\t}\n")
	default:
		fmt.Fprintf(buf, "\t\t*%s = %s\n", ptrSel, zeroValue(typeString(elem)))
	}
}

func isBuiltinNumeric(name string) bool {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128":
		return true
	}
	return false
}

func zeroValue(typeName string) string {
	return "*new(" + typeName + ")"
}

func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return "[" + exprString(t.Len) + "]" + typeString(t.Elt)
	case *ast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	case *ast.InterfaceType:
		return "any"
	default:
		return exprString(expr)
	}
}

func exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, token.NewFileSet(), expr); err != nil {
		return "any"
	}
	return buf.String()
}
